58. Write a function to compute 5/0 and use try/except to catch the 
exceptions.
source code:
def divide_by_zero():
    try:
        result = 5/0
    except ZeroDivisionError:
        print("Error: division by zero")
    else:
        print("Result:", result)

output:
>>> divide_by_zero()
Error: division by zero
